fallacies = {"Formal fallacies":
    {"definition": "A formal fallacy is an error in logic that can be seen in the argument's form.[4] All formal fallacies are specific types of non sequiturs.",
     "Appeal to probability": " a statement that takes something for granted because it would probably be the case (or might be the case).",
     "Argument from fallacy": "assumption that if an argument for some conclusion is fallacious, then the conclusion is false.",
     "Base rate fallacy": "making a probability judgment based on conditional probabilities, without taking into account the effect of prior probabilities.",
     "Conjunction fallacy": "assumption that an outcome simultaneously satisfying multiple conditions is more probable than an outcome satisfying a single one of them.",
     "Masked-man fallacy (illicit substitution of identicals)": "the substitution of identical designators in a true statement can lead to a false one."},
 "Propositional fallacies":
    {"definition": "A propositional fallacy is an error in logic that concerns compound propositions. For a compound proposition to be true, the truth values of its constituent parts must satisfy the relevant logical connectives that occur in it (most commonly: <and>, <or>, <not>, <only if>, <if and only if>). The following fallacies involve inferences whose correctness is not guaranteed by the behavior of those logical connectives, and hence, which are not logically guaranteed to yield true conclusions.",
     "Affirming a disjunct": "concluding that one disjunct of a logical disjunction must be false because the other disjunct is true; A or B; A, therefore not B.",
     "Affirming the consequent": "the antecedent in an indicative conditional is claimed to be true because the consequent is true; if A, then B; B, therefore A.",
     "Denying the antecedent": "the consequent in an indicative conditional is claimed to be false because the antecedent is false; if A, then B; not A, therefore not B."},
 "Quantification fallacies":
    {"definition": "A quantification fallacy is an error in logic where the quantifiers of the premises are in contradiction to the quantifier of the conclusion.",
     "Existential fallacy": "an argument that has a universal premise and a particular conclusion."},
 "Formal syllogistic fallacies":
    {"definition": "logical fallacies that occur in syllogisms.",
     "Affirmative conclusion from a negative premise (illicit negative) ": " a categorical syllogism has a positive conclusion, but at least one negative premise.",
     "Fallacy of exclusive premises ": " a categorical syllogism that is invalid because both of its premises are negative.",
     "Fallacy of four terms (quaternio terminorum) ": " a categorical syllogism that has four terms.",
     "Illicit major ": " a categorical syllogism that is invalid because its major term is not distributed in the major premise but distributed in the conclusion.",
     "Illicit minor ": " a categorical syllogism that is invalid because its minor term is not distributed in the minor premise but distributed in the conclusion.",
     "Negative conclusion from affirmative premises (illicit affirmative) ": " a categorical syllogism has a negative conclusion but affirmative premises.",
     "Fallacy of the undistributed middle ": " the middle term in a categorical syllogism is not distributed.",
     "Modal fallacy ": " confusing possibility with necessity."},
 "Informal fallacies":
    {"definition": " arguments that are fallacious for reasons other than structural (formal) flaws and usually require examination of the argument's content.[16]",
     "Appeal to the stone (argumentum ad lapidem) ": " dismissing a claim as absurd without demonstrating proof for its absurdity",
     "Argument from ignorance (appeal to ignorance, argumentum ad ignorantiam) ": " assuming that a claim is true because it has not been or cannot be proven false, or vice versa",
     "Argument from incredulity (appeal to common sense) ": " I cannot imagine how this could be true; therefore, it must be false",
     "Argument from repetition (argumentum ad nauseam, argumentum ad infinitum) ": " signifies that it has been discussed extensively until nobody cares to discuss it anymore sometimes confused with proof by assertion",
     "Argument from silence (argumentum ex silentio) ": " assuming that a claim is true based on the absence of textual or spoken evidence from an authoritative source, or vice versa",
     "Argument to moderation": " assuming that the compromise between two positions is always correct",
     "Begging the question (petitio principii) ": " providing what is essentially the conclusion of the argument as a premise",
     "Circular reasoning (circulus in demonstrando) ": " the reasoner begins with what he or she is trying to end up with; sometimes called assuming the conclusion.",
     "Circular cause and consequence ": " the consequence of the phenomenon is claimed to be its root cause.",
     "Continuum fallacy (fallacy of the beard, line-drawing fallacy, sorites fallacy, fallacy of the heap, bald man fallacy) ": " improperly rejecting a claim for being imprecise.",
     "Correlative-based fallacies": {
         "Correlation proves causation": " a faulty assumption that, because there is a correlation between two variables, one caused the other.",
         "Suppressed correlative": " a correlative is redefined so that one alternative is made impossible."},
     "Divine fallacy": " arguing that, because something is so incredible/amazing/ununderstandable, it must be the result of superior, divine, alien or paranormal agency.",
     "Double counting": "counting events or occurrences more than once in probabilistic reasoning, which leads to the sum of the probabilities of all cases exceeding unity.",
     "Equivocation":
     {"definition": " the misleading use of a term with more than one meaning (by glossing over which meaning is intended at a particular time).",
      "Ambiguous middle term": " a common ambiguity in syllogisms in which the middle term is equivocated.",
      "Definitional retreat": " changing the meaning of a word to deal with an objection raised against the original wording.",
      "Motte-and-bailey fallacy": " The arguer conflates two similar positions, one modest and easy to defend (the 'motte') and one much more controversial (the 'bailey'). The arguer advances the controversial position, but when challenged, they insist that they are only advancing the more modest position."},
     "Ecological fallacy": " inferences about the nature of specific individuals are based solely upon aggregate statistics collected for the group to which those individuals belong.",
     "Etymological fallacy": " reasoning that the original or historical meaning of a word or phrase is necessarily similar to its actual present-day usage.",
     "Fallacy of accent ": " a specific type of ambiguity that arises when the meaning of a sentence is changed by placing an unusual prosodic stress, or when, in a written passage, it's left unclear which word the emphasis was supposed to fall on.",
     "Fallacy of composition ": " assuming that something true of part of a whole must also be true of the whole.",
     "Fallacy of division ": " assuming that something true of a thing must also be true of all or some of its parts.",
     "False attribution ":
        {"definition": "an advocate appeals to an irrelevant, unqualified, unidentified, biased or fabricated source in support of an argument.",
         "Fallacy of quoting out of context": " refers to the selective excerpting of words from their original context in a way that distorts the source's intended meaning."},
     "False authority": " using an expert of dubious credentials or using only one opinion to sell a product or idea. Related to the appeal to authority fallacy.",
     "False dilemma": " two alternative statements are held to be the only possible options when in reality there are more.",
     "False equivalence": " describing a situation of logical and apparent equivalence, when in fact there is none.",
     "Fallacy of many questions": "someone asks a question that presupposes something that has not been proven or accepted by all the people involved. This fallacy is often used rhetorically so that the question limits direct replies to those that serve the questioner's agenda.",
     "Fallacy of the single cause": "it is assumed that there is one, simple cause of an outcome when in reality it may have been caused by a number of only jointly sufficient causes.",
     "Furtive fallacy": "outcomes are asserted to have been caused by the malfeasance of decision makers.",
     "Gambler's fallacy": "the incorrect belief that separate, independent events can affect the likelihood of another random event. If a fair coin lands on heads 10 times in a row, the belief that it is 'due to the number of times it had previously landed on tails' is incorrect.",
     "Historian's fallacy": "occurs when one assumes that decision makers of the past viewed events from the same perspective and having the same information as those subsequently analyzing the decision. (Not to be confused with presentism, which is a mode of historical analysis in which present-day ideas, such as moral standards, are projected into the past.)",
     "Historical fallacy": "a set of considerations is thought to hold good only because a completed process is read into the content of the process which conditions this completed result.",
     "Homunculus fallacy": "a 'middle-man' is used for explanation; this sometimes leads to regressive middle-men. Explains without actually explaining the real nature of a function or a process. Instead, it explains the concept in terms of the concept itself, without first defining or explaining the original concept. Explaining thought as something produced by a little thinker, a sort of homunculus inside the head, merely explains it as another kind of thinking (as different but the same).",
     "Inflation of conflict": "The experts of a field of knowledge disagree on a certain point, so the scholars must know nothing, and therefore the legitimacy of their entire field is put to question.",
     "If-by-whiskey": "an argument that supports both sides of an issue by using terms that are selectively emotionally sensitive.",
     "Incomplete comparison": "insufficient information is provided to make a complete comparison.",
     "Inconsistent comparison": "different methods of comparison are used, leaving one with a false impression of the whole comparison.",
     "Intentionality fallacy": " the insistence that the ultimate meaning of an expression must be consistent with the intention of the person from whom the communication originated (e.g. a work of fiction that is widely received as a blatant allegory must necessarily not be regarded as such if the author intended it not to be so.)[49]",
     "Ignoratio elenchi (irrelevant conclusion, missing the point)": " an argument that may in itself be valid, but does not address the issue in question.[50]",
     "Kettle logic": "using multiple, jointly inconsistent arguments to defend a position.[dubious - discuss]",
     "Ludic fallacy": " the belief that the outcomes of non-regulated random occurrences can be encapsulated by a statistic; a failure to take into account unknown unknowns in determining the probability of events taking place.[51]",
     "McNamara fallacy (quantitative fallacy)": " making a decision based only on quantitative observations, discounting all other considerations.",
     "Mind projection fallacy": "one's subjective judgments are 'projected' to be inherent properties of an object, rather than being related to personal perception of that object.",
     "Moralistic fallacy": "inferring factual conclusions from purely evaluative premises in violation of fact-value distinction. For instance, inferring is from ought is an instance of moralistic fallacy. Moralistic fallacy is the inverse of naturalistic fallacy.",
     "Moving the goalposts": "argument in which evidence presented in response to a specific claim is dismissed and some other (often greater) evidence is demanded.",
     "Naturalistic fallacy": "inferring evaluative conclusions from purely factual premises in violation of fact-value distinction. For instance, inferring ought from is (sometimes referred to as the is-ought fallacy) is an instance of naturalistic fallacy.",
     "Nirvana fallacy (perfect solution fallacy)": "solutions to problems are rejected because they are not perfect.",
     "Onus probandi": "the burden of proof is on the person who makes the claim, not on the person who denies (or questions the claim). It is a particular case of the argumentum ad ignorantiam fallacy, here the burden is shifted on the person defending against the assertion. Also known as shifting the burden of proof.",
     "Post hoc ergo propter hoc": "(faulty cause/effect, coincidental correlation, correlation without causation) : X happened, then Y happened; therefore X caused Y. The Loch Ness Monster has been seen in this loch. Something tipped our boat over; it's obviously the Loch Ness Monster.",
     "Proof by assertion": "a proposition is repeatedly restated regardless of contradiction; sometimes confused with argument from repetition (argumentum ad infinitum, argumentum ad nauseam)",
     "Prosecutor's fallacy": "a low probability of false matches does not mean a low probability of some false match being found.",
     "Proving too much": "sing a form of argument that, if it were valid, could be used to reach an additional, undesirable conclusion.",
     "Psychologist's fallacy": "an observer presupposes the objectivity of his own perspective when analyzing a behavioral event.",
     "Red herring": "a speaker attempts to distract an audience by deviating from the topic at hand by introducing a separate argument the speaker believes is easier to speak to.",
     "Referential fallacy": "assuming all words refer to existing things and that the meaning of words reside within the things they refer to, as opposed to words possibly referring to no real object or that the meaning of words often comes from how we use them.",
     "Regression fallacy": "ascribes cause where none exists. The flaw is failing to account for natural fluctuations. It is frequently a special kind of post hoc fallacy.",
     "Reification": "a fallacy of ambiguity, when an abstraction (abstract belief or hypothetical construct) is treated as if it were a concrete, real event or physical entity. In other words, it is the error of treating as a 'real thing' something that is not a real thing, but merely an idea.",
     "Retrospective determinism": "the argument that because an event has occurred under some circumstance, the circumstance must have made its occurrence inevitable.",
     "Special pleading": "a proponent of a position attempts to cite something as an exemption to a generally accepted rule or principle without justifying the exemption.",
     "Wrong direction": "cause and effect are reversed. The cause is said to be the effect and vice versa."},
 "Faulty generalizations":
    {"definition": "reach a conclusion from weak premises. Unlike fallacies of relevance, in fallacies of defective induction, the premises are related to the conclusions yet only weakly buttress the conclusions. A faulty generalization is thus produced.",
     "Accident": "an exception to a generalization is ignored.",
     "No true Scotsman": "makes a generalization true by changing the generalization to exclude a counterexample.",
     "Cherry picking": "act of pointing at individual cases or data that seem to confirm a particular position, while ignoring a significant portion of related cases or data that may contradict that position.",
     "Survivorship bias": "a small number of survivors of a given process are actively promoted while completely ignoring a large number of failures",
     "False analogy": "an argument by analogy in which the analogy is poorly suited.",
     "Hasty generalization ": "basing a broad conclusion on a small sample or the making of a determination without all of the information required to do so.",
     "Inductive fallacy": "A more general name to some fallacies, such as hasty generalization. It happens when a conclusion is made of premises that lightly support it.",
     "Misleading vividness": "involves describing an occurrence in vivid detail, even if it is an exceptional occurrence, to convince someone that it is a problem.",
     "Overwhelming exception": "an accurate generalization that comes with qualifications that eliminate so many cases that what remains is much less impressive than the initial statement might have led one to assume.",
     "Thought-terminating cliché": "a commonly used phrase, sometimes passing as folk wisdom, used to quell cognitive dissonance, conceal lack of thought-entertainment, move on to other topics etc. but in any case, end the debate with a cliché—not a point."},
 "Red herring":
    {"definition": "argument given in response to another argument, which is irrelevant and draws attention away from the subject of argument.",
     "Ad hominem":
        {"definition": "attacking the arguer instead of the argument.",
         "Poisoning the well": "a subtype of ad hominem presenting adverse information about a target person with the intention of discrediting everything that the target person says.",
         "Abusive fallacy": "verbally abusing the opponent rather than arguing about the originally proposed argument.",
         "Appeal to motive": "dismissing an idea by questioning the motives of its proposer.",
         "Kafka-trapping": "A sophistical and unfalsifiable form of argument that attempts to overcome an opponent by inducing a sense of guilt and using the opponent's denial of guilt as further evidence of guilt.",
         "Tone policing": "focusing on emotion behind (or resulting from) a message rather than the message itself as a discrediting tactic.",
         "Traitorous critic fallacy": "a critic's perceived affiliation is portrayed as the underlying reason for the criticism and the critic is asked to stay away from the issue altogether."},
     "Appeal to authority":
        {"definition": "an assertion is deemed true because of the position or authority of the person asserting it.",
         "Appeal to accomplishment": "an assertion is deemed true or false based on the accomplishments of the proposer.",
         "Courtier's Reply": "a criticism is dismissed by claiming that the critic lacks sufficient knowledge, credentials, or training to credibly comment on the subject matter."},
     "Appeal to consequences": "the conclusion is supported by a premise that asserts positive or negative consequences from some course of action in an attempt to distract from the initial discussion.",
     "Appeal to emotion":
        {"definition": "an argument is made due to the manipulation of emotions, rather than the use of valid reasoning.",
         "Appeal to fear": "an argument is made by increasing fear and prejudice towards the opposing side",
         "Appeal to flattery": "an argument is made due to the use of flattery to gather support.",
         "Appeal to pity": "an argument attempts to induce pity to sway opponents.",
         "Appeal to ridicule": "an argument is made by presenting the opponent's argument in a way that makes it appear ridiculous.",
         "Appeal to spite": "an argument is made through exploiting people's bitterness or spite towards an opposing party.",
         "Wishful thinking": "a decision is made according to what might be pleasing to imagine, rather than according to evidence or reason."},
     "Appeal to nature": "judgment is based solely on whether the subject of judgment is 'natural' or 'unnatural'. (Sometimes also called the 'naturalistic fallacy', but is not to be confused with the other fallacies by that name)",
     "Appeal to novelty": "a proposal is claimed to be superior or better solely because it is new or modern.",
     "Appeal to poverty": "supporting a conclusion because the arguer is poor (or refuting because the arguer is wealthy). (Opposite of appeal to wealth.)",
     "Appeal to tradition": "a conclusion supported solely because it has long been held to be true.",
     "Appeal to wealth": "supporting a conclusion because the arguer is wealthy (or refuting because the arguer is poor). (Sometimes taken together with the appeal to poverty as a general appeal to the arguer's financial situation.)",
     "Argumentum ad baculum": "an argument made through coercion or threats of force to support position.",
     "Argumentum ad populum": "a proposition is claimed to be true or good solely because majority or many people believe it to be so.",
     "Association fallacy": "arguing that because two things share (or are implied to share) some property, they are the same.",
     "Bare assertion fallacy": "a claim that is presented as true without support, as self-evidently true, or as dogmatically true. This fallacy relies on the implied expertise of the speaker or on an unstated truism.",
     "Bulverism": "inferring why an argument is being used, associating it to some psychological reason, then assuming it is invalid as a result. It is wrong to assume that if the origin of an idea comes from a biased mind, then the idea itself must also be a falsehood.",
     "Chronological snobbery": "a thesis is deemed incorrect because it was commonly held when something else, clearly false, was also commonly held.",
     "Fallacy of relative privation": "dismissing an argument or complaint due to the existence of more important problems in the world, regardless of whether those problems bear relevance to the initial argument. First World problems are a subset of this fallacy.",
     "Genetic fallacy": "a conclusion is suggested based solely on something or someone's origin rather than its current meaning or context.",
     "Judgmental language": "insulting or pejorative language to influence the recipient's judgment.",
     "Moralistic fallacy": "statements about what is, on the basis of claims about what ought to be.",
     "Naturalistic fallacy": "claims about what ought to be, on the basis of statements about what is.",
     "Pooh-pooh": "dismissing an argument perceived unworthy of serious consideration.",
     "Straw man fallacy": "an argument based on misrepresentation of an opponent's position.",
     "Texas sharpshooter fallacy": "improperly asserting a cause to explain a cluster of data.",
     "Tu quoque": "the argument states that a certain position is false or wrong or should be disregarded because its proponent fails to act consistently in accordance with that position.",
     "Two wrongs make a right": "occurs when it is assumed that if one wrong is committed, an 'equal but opposite' wrong will cancel it out.",
     "Vacuous truth": "a claim that is technically true but meaningless, in the form of claiming that no A in B has C, when there are no A in B. For example, claiming that no mobile phones in the room are on when there are no mobile phones in the room at all."}
 }
